import {
  productOne,
  productTwo,
  productThree,
  productFour,
  productFive,
  productSix,
  productSeven,
} from "../assets/images";

export const productData = [
  {
    id: 1001,
    title: "Bag",
    description: "Black new super bag",
    brand: "Unknown",
    image: productOne,
    category: "Bag",
    price: 150,
    color: ["000", "e6e600", "00ee00", "e60000"],
    size: ["sm", "md", "lg", "xl"],
  },
  {
    id: 1002,
    title: "Shoes",
    description: "New design and colors",
    brand: "Adidas",
    image: productTwo,
    category: "Shoes",
    price: 200,
    color: ["e60000", "000", "e6e600", "345454"],
    size: ["md", "lg", "sm"],
  },
  {
    id: 1003,
    title: "Bag",
    description: "Black new super bag",
    brand: "Unknown",
    image: productThree,
    category: "Bag",
    price: 150,
    color: ["000", "e6e600", "00ee00", "e60000"],
    size: ["sm", "md", "lg", "xl"],
  },
  {
    id: 1004,
    title: "Shoes",
    description: "New design and colors",
    brand: "Adidas",
    image: productFour,
    category: "Shoes",
    price: 200,
    color: ["e60000", "000", "e6e600", "345454"],
    size: ["md", "lg", "sm"],
  },
  {
    id: 1005,
    title: "Bag",
    description: "Black new super bag",
    brand: "Unknown",
    image: productFive,
    category: "Bag",
    price: 150,
    color: ["000", "e6e600", "00ee00", "e60000"],
    size: ["sm", "md", "lg", "xl"],
  },
  {
    id: 1006,
    title: "Shoes",
    description: "New design and colors",
    brand: "Adidas",
    image: productSix,
    category: "Shoes",
    price: 200,
    color: ["e60000", "000", "e6e600", "345454"],
    size: ["md", "lg", "sm"],
  },
  {
    id: 1007,
    title: "Bag",
    description: "Black new super bag",
    brand: "Unknown",
    image: productSeven,
    category: "Bag",
    price: 150,
    color: ["000", "e6e600", "00ee00", "e60000"],
    size: ["sm", "md", "lg", "xl"],
  },
  {
    id: 1008,
    title: "Shoes",
    description: "New design and colors",
    brand: "Adidas",
    image: productTwo,
    category: "Shoes",
    price: 200,
    color: ["e60000", "000", "e6e600", "345454"],
    size: ["md", "lg", "sm"],
  },
];
